server:
  port: 8080

spring:
  application:
    name: order-api
  kafka:
    bootstrap-servers: 192.168.100.131:9092,192.168.100.131:9093,192.168.100.131:9094
    template:
      default-topic: order-placed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO